# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT       += core gui sql network xml multimedia multimediawidgets quickwidgets qml quick

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += debug
CONFIG += qzxing_qml
CONFIG += qzxing_multimedia
include(qzxing-master/src/qzxing.pri)

TARGET = UNARetail
TEMPLATE = app
DEFINES += QT_VERSION5X CAMERA_SUPPORT
# Default rules for deployment.
QMAKE_LINK += -nostdlib++
DEPENDPATH += .
TRANSLATIONS += translations/unaretail_ru.ts \
    translations/unaretail_ro.ts \
    translations/unaretail_en.ts

QML_IMPORT_PATH = D:\Lib\Qt\5.12.2
QML_DESIGNER_IMPORT_PATH =D:\Lib\Qt\5.12.2
RESOURCES += resources.qrc




TRANSLATIONS += translations/uamobi_en.ts translations/uamobi_ro.ts translations/uamobi_ru.ts

DISTFILES += \
    android-sources/AndroidManifest.xml \
    android-sources/build.gradle \
    android-sources/gradle/wrapper/gradle-wrapper.jar \
    android-sources/gradle/wrapper/gradle-wrapper.properties \
    android-sources/gradlew \
    android-sources/gradlew.bat \
    android-sources/res/drawable-hdpi/icon.png \
    android-sources/res/drawable-ldpi/icon.png \
    android-sources/res/drawable-mdpi/icon.png \ \
    android-sources/res/values/libs.xml \
    uamobi_en.qm \
    uamobi_en.ts \
    uamobi_ro.qm \
    uamobi_ro.ts \
    uamobi_ru.qm \
    uamobi_ru.ts \
    widgets/CameraBranch/main.qml \
    widgets/Widget tree structure.txt \
    widgets/utils/widgets - Ярлык.lnk/Widget tree structure.txt

ANDROID_PACKAGE_SOURCE_DIR = $$PWD/android-sources

HEADERS += \
    Datacore/AbsEntity.h \
    Datacore/BarcodeEntity.h \
    Datacore/DataEntities.h \
    Datacore/PricedBarcodeEntity.h \
    Datacore/ShortBarcodeEntity.h \
    dataFormats/dataformatcore.h \
    dataFormats/dataformater.h \
    dataFormats/formats.h \
    dataproviders/BackupingEngine.h \
    dataproviders/DataAsyncLoader.h \
    dataproviders/TableHandlers.h \
    dataproviders/abstractdataprovider.h \
    dataproviders/sqldataprovider.h \
    debugtrace.h \
    externalCommunication/communicationCore.h \
    externalCommunication/tohttp.h \
    externalCommunication/tolocalmemory.h \
    widgets/CameraBranch/CameraWidget.h \
    widgets/CameraBranch/MyVideoFilter.h \
    widgets/CameraBranch/MyVideoFilterRunnable.h \
    widgets/ControlsMiniwidgets/ControlTranslator.h \
    widgets/ControlsMiniwidgets/DateTimeControl.h \
    widgets/ControlsMiniwidgets/LabelControl.h \
    widgets/ControlsMiniwidgets/QuantityControl.h \
    widgets/ControlsMiniwidgets/StringControl.h \
    widgets/ControlsMiniwidgets/abs_control.h \
    widgets/CoreWidget.h \
    widgets/InventoryBranch/InventoryWidget.h \
    widgets/MainPage/MainPageWidget.h \
    widgets/MultibranchWidgets/BarcodeRedactingWidget.h \
    widgets/MultibranchWidgets/ReceiveWidget.h \
    widgets/MultibranchWidgets/ScanedStorageWidget.h \
    widgets/MultibranchWidgets/ScaningCameraWidget.h \
    widgets/MultibranchWidgets/ScaningWidget.h \
    widgets/MultibranchWidgets/SendSettings.h \
    widgets/MultibranchWidgets/SendingDataPickerWidget.h \
    widgets/MultibranchWidgets/innerSettingsForm.h \
    widgets/PriceBranch/PriceBranchRootWidget.h \
    widgets/PriceBranch/PriceBranchScaningWidget.h \
    widgets/PriceBranch/PriceBranchWidget.h \
    widgets/PriceBranch/PriceScaningWidget.h \
    widgets/PriceBranch/PricedBarcodeRedacting.h \
    widgets/SearchBranch/SearchWidget.h \
    widgets/SettingsForm.h \
    widgets/SettingsWidgets/DatabaseSettings.h \
    widgets/SettingsWidgets/GeneralSettings.h \
    widgets/SettingsWidgets/QuickSendSettings.h \
    widgets/SettingsWidgets/ScaningSettings.h \
    widgets/SettingsWidgets/SearchDatabaseSettings.h \
    widgets/SettingsWidgets/SerializationSettings.h \
    widgets/SettingsWidgets/ViewSettings.h \
    widgets/SimpleBranch/SimpleBranchWidget.h \
    widgets/SupplyBranch/SuppliesWidget.h \
    widgets/parents/AbstractCameraWidget.h \
    widgets/parents/AbstractScaningWidget.h \
    widgets/parents/BranchRootWidget.h \
    widgets/parents/abstractNodeInterface.h \
    widgets/parents/inframedWidget.h \
    widgets/utils/BarcodeObserver.h \
    widgets/utils/BigButtonsSpinbox.h \
    widgets/utils/ElementsStyles.h \
    widgets/utils/EventsAndFilters.h \
    widgets/utils/GlobalAppSettings.h \
    widgets/utils/MegaIconButton.h \
    widgets/utils/UniformBarcode.h \
    widgets/utils/VirtualBarcodeKeyboard.h \
    widgets/utils/ZebraListItemDelegate.h

SOURCES += \
    Datacore/AbsEntity.cpp \
    Datacore/BarcodeEntity.cpp \
    Datacore/DataEntities.cpp \
    Datacore/PricedBarcodeEntity.cpp \
    Datacore/ShortBarcodeEntity.cpp \
    dataFormats/dataformatcore.cpp \
    dataFormats/dataformater.cpp \
    dataFormats/formats.cpp \
    dataproviders/BackupingEngine.cpp \
    dataproviders/DataAsyncLoader.cpp \
    dataproviders/TableHandlers.cpp \
    dataproviders/abstractdataprovider.cpp \
    dataproviders/sqldataprovider.cpp \
    debugtrace.cpp \
    externalCommunication/communicationCore.cpp \
    externalCommunication/tohttp.cpp \
    externalCommunication/tolocalmemory.cpp \
    main.cpp \
    widgets/CameraBranch/CameraWidget.cpp \
    widgets/CameraBranch/MyVideoFilter.cpp \
    widgets/CameraBranch/MyVideoFilterRunnable.cpp \
    widgets/ControlsMiniwidgets/ControlTranslator.cpp \
    widgets/ControlsMiniwidgets/DateTimeControl.cpp \
    widgets/ControlsMiniwidgets/LabelControl.cpp \
    widgets/ControlsMiniwidgets/QuantityControl.cpp \
    widgets/ControlsMiniwidgets/StringControl.cpp \
    widgets/ControlsMiniwidgets/abs_control.cpp \
    widgets/CoreWidget.cpp \
    widgets/InventoryBranch/InventoryWidget.cpp \
    widgets/MainPage/MainPageWidget.cpp \
    widgets/MultibranchWidgets/BarcodeRedactingWidget.cpp \
    widgets/MultibranchWidgets/ReceiveWidget.cpp \
    widgets/MultibranchWidgets/ScanedStorageWidget.cpp \
    widgets/MultibranchWidgets/ScaningCameraWidget.cpp \
    widgets/MultibranchWidgets/ScaningWidget.cpp \
    widgets/MultibranchWidgets/SendSettings.cpp \
    widgets/MultibranchWidgets/SendingDataPickerWidget.cpp \
    widgets/MultibranchWidgets/innerSettingsForm.cpp \
    widgets/PriceBranch/PriceBranchRootWidget.cpp \
    widgets/PriceBranch/PriceBranchScaningWidget.cpp \
    widgets/PriceBranch/PriceBranchWidget.cpp \
    widgets/PriceBranch/PriceScaningWidget.cpp \
    widgets/PriceBranch/PricedBarcodeRedacting.cpp \
    widgets/SearchBranch/SearchWidget.cpp \
    widgets/SettingsForm.cpp \
    widgets/SettingsWidgets/DatabaseSettings.cpp \
    widgets/SettingsWidgets/GeneralSettings.cpp \
    widgets/SettingsWidgets/QuickSendSettings.cpp \
    widgets/SettingsWidgets/ScaningSettings.cpp \
    widgets/SettingsWidgets/SearchDatabaseSettings.cpp \
    widgets/SettingsWidgets/SerializationSettings.cpp \
    widgets/SettingsWidgets/ViewSettings.cpp \
    widgets/SimpleBranch/SimpleBranchWidget.cpp \
    widgets/SupplyBranch/SuppliesWidget.cpp \
    widgets/parents/AbstractCameraWidget.cpp \
    widgets/parents/AbstractScaningWidget.cpp \
    widgets/parents/BranchRootWidget.cpp \
    widgets/parents/abstractNodeInterface.cpp \
    widgets/parents/inframedWidget.cpp \
    widgets/utils/BarcodeObserver.cpp \
    widgets/utils/BigButtonsSpinbox.cpp \
    widgets/utils/ElementsStyles.cpp \
    widgets/utils/EventsAndFilters.cpp \
    widgets/utils/GlobalAppSettings.cpp \
    widgets/utils/MegaIconButton.cpp \
    widgets/utils/VirtualBarcodeKeyboard.cpp \
    widgets/utils/ZebraListItemDelegate.cpp
